### ISSUE TITLE
support multi-day events

### ISSUE THREAD

**Issue by insanum** [insanum/gcalcli#12]
gcalcli should show multi-day events across each day for agenda, calw, and calm outputs.

If someone wants to give it a shot... go for it! :-)

**Comment by tmerse** [comment]
Would love to see this aswell.

**Comment by slawqo** [comment]
Hello, I will try to add such feature and make pull request.

**Comment by ZaxonXP** [comment]
I installed the version from sources which has these additional options like --military, --monday, ect. When I got your version of gcalcli file then indeed the multiday event is displayed for each day, but I do not have the extra options. How can I merge your code to the main branch using git to have a "both words"?

I have to add that I am not so experienced in the git commands.

**Comment by slawqo** [comment]
Hello,

I made this patch quite long time ago. Probably options which You are talking about were introduced later and now You should rebase my branch on top of current master branch. Then You should have actual version with my patch also.

> Wiadomość napisana przez ZaxonXP <notifications@github.com> w dniu 26.04.2017, o godz. 11:40:
> 
> I installed the version from sources which has these additional options like --military, --monday, ect. When I got your version of gcalcli file then indeed the multiday event is displayed for each day, but I do not have the extra options. How can I merge your code to the main branch using git to have a "both words"?
> 
> I have to add that I am not so experienced in the git commands.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


—
Best regards
Slawek Kaplonski
slawek@kaplonski.pl

**Comment by jcrowgey** [comment]
I believe we now support mulit day events, I saw @slawqo's comments in the code when I was refactoring recently.  Thanks!  I believe this issue is resolved.

**Comment by ChrisCheney** [comment]
@jcrowgey

It appears it was only fixed for calm, and calw in 4.0.0a4. agenda still doesn't show multiday events correctly.

**Comment by ChrisCheney** [comment]
Actually looking closer at 4.0.0a4 output for calm, and calw it appears they don't always show multiday events correctly either. Several of my multiday events for the next month don't show on the correct days particularly on weekends.

I can't post the output publicly since its a work calendar but if you want debug details I can send it to you privately.

**Comment by jcrowgey** [comment]
@ChrisCheney Thanks for taking a close look.  it would be convenient if you could show us the form of the issue here publically, possibly by changing or obscuring sensitive information.  That would potentially make this issue something that could be worked on (and we could repoen the ticket).  Is there a way to replicate what you found without using sensitive information?

If you want to send me the details privately, feel free to use PGP email, my key is available on the public keyservers.  But I want to emphasize the importance of the community here---I'm only one of many people working on this project (and I'm particularly swamped with other things at the moment).

**Comment by ChrisCheney** [comment]
Ok, so I can reproduce the problem easily. I used a different users blank google calendar to test with.

The steps are:

1. Create a multiday event in Google Calendar on the weekend.
  a. eg a multiday event 'work' on Nov 17-18 (spans 2 days)
2. Run gcalcli --refresh agenda "2018-11-11" "2018-11-25"
  a. Note it only shows the first day, Nov 17, not Nov 18
3. Run gcalcli --refresh calm
  a. Note it shows 'work' on Nov 11 and Nov 18 instead of Nov 17, Nov 18
4. Run gcalcli --refresh calw 2
 a. Note it shows 'work' on Nov 11 and Nov 18 instead of Nov 17, Nov 18

So it looks like there are actually two separate bugs.
1. calm/calw shows a multiday event on the wrong days. This appears to be specific to weekends.
2. agenda never appears to show any days after the initial one. This happens even on regular week days.

If you need any more information from me please let me know.

**Comment by jcrowgey** [comment]
Thanks @ChrisCheney 

I'll take a look at this when I get a chance. We may want to close this issue and open two new bugs, since in theory we have done the work to support multi-day events, fixing some new bugs you found isn't a different task.

But for now I'll just reopen this issue so that we can be reminded that we need to look into this.

**Comment by amacfie** [comment]
Creation of multi-day events is an issue too
